version: '3.1'
services:
  application:
    build: ./docker
    image: leafphp/docker
    ports:
      - '8080:80'
    volumes:
      - .:/var/www

  pgsql:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: leafphp
      POSTGRES_PASSWORD: leafphp
      POSTGRES_DB: leafphp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
