version: '3.1'
services:
  application:
    build: ./docker
    image: leafphp/docker
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
    networks:
      - mq
      - pgsql_db

  pgp_server:
    build:
      context: ./pgp_server
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pgp_server:/pgp_server
    networks:
      - mq

  pgsql:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pgsql_db

  mailcatcher:
    container_name: mailcatcher_container
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  lavinmq:
    container_name: lavinmq_container
    image: cloudamqp/lavinmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - mq

volumes:
  pgdata:

networks:
  mq:
    driver: bridge
  pgsql_db:
    driver: bridge
